apiVersion: apps/v1
kind: Deployment
metadata:
  name: appy-deployment
spec:
  selector:
    matchLabels:
      app: appy
  replicas: 1
  template:
    metadata:
      labels:
        app: appy
    spec:
      containers:
        - name: appy
          image: appy:0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000